name: BuildCore
on:
  workflow_call:
    inputs:
      inno:
        required: false
        type: boolean
        default: false
      sign:
        required: false
        type: boolean
        default: false

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4

      - name: 设置 Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.0"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U nuitka==2.6.8 zstandard ordered-set

      - name: 编译
        run: python -m nuitka --mingw64 --assume-yes-for-downloads --standalone --windows-uac-admin --remove-output --windows-console-mode="disable" --jobs=8 --enable-plugins="pyqt5" --output-dir="dist" ...

      - name: 移动文件
        run: move WCMain dist/wincleaner.dist/WCMain

      - name: 上传未签名的主程序
        id: upload-unsigned-exe
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-exe
          path: dist/wincleaner.dist/wincleaner.exe

      - name: 提交代码签名请求
        if: ${{ inputs.sign }}
        id: submit-signing-request
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: "WindowsCleaner"
          signing-policy-slug: "release-signing"
          artifact-configuration-slug: "sign-exezip"
          github-artifact-id: ${{ steps.upload-unsigned-exe.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: dist/wincleaner.dist

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner
          path: dist

      - name: 生成安装包
        if: ${{ inputs.inno }}
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: script.iss
          options: /O+

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner-amd64-Setup
          path: releases/*.exe
