name: 编译
run-name: 编译

on:
  workflow_dispatch:
    inputs:
      inno:
        description: "生成安装包"
        type: boolean
        default: false
      sign:
        description: "签名"
        type: boolean
        default: false
      msvc:
        description: "使用 MSVC 编译器（推荐）"
        type: boolean
        default: true
      debug:
        description: "编译时显示终端窗口（便于调试）"
        type: boolean
        default: false

jobs:
  Build:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4

      - name: 设置 Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U nuitka==2.5.1 zstandard ordered-set

      # 配置 MSVC 环境变量（如选择 MSVC 编译器）
      - name: 配置 MSVC
        if: ${{ inputs.msvc }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: 编译
        run: |
          $NuitkaCmd = "python -m nuitka --standalone --assume-yes-for-downloads --enable-plugin=pyqt5 --output-dir=dist --follow-imports --windows-uac-admin --remove-output --jobs=8 --windows-icon-from-ico=icon.ico --company-name='DaYe' --product-name='WindowsCleaner' --file-version='5.0.0' --product-version='5.0' --file-description='WindowsCleaner' --copyright='DaYe' --trademarks='DaYe' wincleaner.py"
          if ("${{ inputs.debug }}".ToLower() -eq "true") { $NuitkaCmd += " --windows-console" }
          if ("${{ inputs.msvc }}".ToLower() -eq "false") { $NuitkaCmd += " --mingw64" }
          echo "Nuitka build command: $NuitkaCmd"
          Invoke-Expression $NuitkaCmd

      - name: 移动文件
        run: move WCMain dist/wincleaner.dist/WCMain

      - name: 上传未签名的主程序
        id: upload-unsigned-exe
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-exe
          path: dist/wincleaner.dist/wincleaner.exe

      - name: 提交代码签名请求
        if: ${{ inputs.sign }}
        id: submit-signing-request
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: "WindowsCleaner"
          signing-policy-slug: "release-signing"
          artifact-configuration-slug: "sign-exezip"
          github-artifact-id: ${{ steps.upload-unsigned-exe.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: dist/wincleaner.dist

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner
          path: dist

      - name: 生成安装包
        if: ${{ inputs.inno }}
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: script.iss
          options: /O+

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner-amd64-Setup
          path: releases/*.exe
