name: Build with Nuitka

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
        input-file: wincleaner.py
        arguments: >
          --enable-plugin=pyqt5 
          --windows-icon-from-ico=WCMain/resource/imgs/icon.ico
          --windows-uac-admin
          --remove-output
          --output-dir=dist

    - name: Package artifacts
      run: |
        Compress-Archive -Path dist/wincleaner.dist/* -DestinationPath WindowsCleaner-${{ github.run_number }}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: WindowsCleaner
        path: |
          *.zip
          dist/
