name: 发行
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "版本号"
        required: true
        default: vx.x.x
      sign:
        description: "签名"
        type: boolean
        default: false

jobs:
  Build:
    uses: ./.github/workflows/Build.yml
    with:
      inno: true
      sign: ${{ inputs.sign }}

  Release:
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 下载附件
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 压缩绿化版
        run: |
          zip -r WindowsCleaner.zip artifacts/WindowsCleaner

      - name: 发行
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          draft: false
          make_latest: true
          files: |
            WindowsCleaner.zip
            artifacts/WindowsCleaner-amd64-Setup/*.exe
