name: 发行
run-name: 发行
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "版本号"
        required: true
        default: vx.x.x

jobs:
  Build:
    name: 编译
    runs-on: windows-2022
    permissions: write-all
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4
      - name: 设置 Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U nuitka==2.5.1 zstandard ordered-set
      - name: 编译
        run: python -m nuitka --mingw64 --assume-yes-for-downloads --standalone --windows-uac-admin --remove-output --windows-console-mode="disable" --nofollow-imports --jobs=8 --enable-plugins="pyqt5" --output-dir="dist" --main="wincleaner.py" --windows-icon-from-ico="icon.ico" --company-name="DaYe" --product-name="WindowsCleaner" --file-version="5.0.0" --product-version="5.0" --file-description="WindowsCleaner" --copyright="DaYe" --trademarks="DaYe"
      - name: 移动文件
        run: move WCMain dist/main.dist/WCMain
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner
          path: dist
      - name: 生成安装包
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: script.iss
          options: /O+
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner-amd64-Setup
          path: releases/*.exe

  Release:
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 下载附件
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 压缩绿化版
        run: |
          zip -r WindowsCleaner.zip artifacts/WindowsCleaner

      - name: 发行
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          draft: false
          make_latest: true
          files: |
            WindowsCleaner.zip
            artifacts/WindowsCleaner-amd64-Setup/*.exe
